from typing import Protocol, Optional, List


class Repository(Protocol):
    def get(self, collection: str, id: str) -> dict | None: ...
    def put(self, collection: str, item: dict) -> str: ...
    def delete(self, collection: str, id: str) -> bool: ...
    def query(self, collection: str, filters: dict | None, limit: int, offset: int) -> tuple[list[dict], int]: ...
    def query_with_date_filters(
        self,
        collection: str,
        filters: dict | None = None,
        date_filters: dict | None = None,
        limit: int = 50,
        offset: int = 0
    ) -> tuple[list[dict], int]: ...


class AssessmentRepository(Protocol):
    """评估仓储接口"""
    async def create(self, assessment) -> str: ...
    async def get(self, assessment_id: str): ...
    async def update(self, assessment) -> bool: ...
    async def find_by_user(self, user_id: str, limit: int = 10) -> list: ...


class QuestionRepository(Protocol):
    """题库仓储接口"""
    async def get(self, question_id: str): ...
    async def find_closest(self, level: str, type: str, exclude_ids: List[str]): ...
    async def find_by_level(self, level: str, limit: int = 20) -> list: ...
